// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ContentDiv: typeof import('./components/widgets/ContentDiv.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElInput: typeof import('element-plus/es')['ElInput']
    FlexLayout: typeof import('./components/FlexLayout.vue')['default']
    FlexNode: typeof import('./components/FlexNode.vue')['default']
    GridLayout: typeof import('./components/GridLayout.vue')['default']
    NestedDraggable: typeof import('./components/nestedDraggable.vue')['default']
  }
}
